// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Viber.Models;

[Table("ContentContainer")]
public partial class ContentContainer
{
    [Key]
    [Column("ContentContainter_Id")]
    public int ContentContainterId { get; set; }

    [Column("Moodboard_Id")]
    public int MoodboardId { get; set; }

    [Required]
    [StringLength(300)]
    [Unicode(false)]
    public string Title { get; set; }

    [StringLength(300)]
    [Unicode(false)]
    public string Music { get; set; }

    [StringLength(300)]
    [Unicode(false)]
    public string Movie { get; set; }

    [StringLength(300)]
    [Unicode(false)]
    public string YouTubeLink { get; set; }

    [StringLength(300)]
    [Unicode(false)]
    public string PictureLink { get; set; }

    [StringLength(1000)]
    [Unicode(false)]
    public string ContentText { get; set; }

    [ForeignKey("MoodboardId")]
    [InverseProperty("ContentContainers")]
    public virtual Moodboard Moodboard { get; set; }
}