// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Viber.Models;

[Table("ContentContainer")]
public partial class ContentContainer
{
    [Key]
    [Column("ContentContainter_Id")]
    public int ContentContainterId { get; set; }

    [Column("Moodboard_Id")]
    public int MoodboardId { get; set; }

    [StringLength(300)]
    [Unicode(false)]
    public string Type { get; set; }

    [StringLength(300)]
    [Unicode(false)]
    public string Link { get; set; }

    [Column("Order_Id")]
    public int? OrderId { get; set; }

    [Column("Background_Color")]
    [StringLength(7)]
    [Unicode(false)]
    public string BackgroundColor { get; set; }

    [Column("Text_Color")]
    [StringLength(7)]
    [Unicode(false)]
    public string TextColor { get; set; }

    [ForeignKey("MoodboardId")]
    [InverseProperty("ContentContainers")]
    public virtual Moodboard Moodboard { get; set; }
}