// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Viber.Models;

[Table("MoodboardSubTag")]
public partial class MoodboardSubTag
{
    [Key]
    [Column("MoodboardSubtag_Id")]
    public int MoodboardSubtagId { get; set; }

    [Column("Moodboard_Id")]
    public int MoodboardId { get; set; }

    [Column("Subtag_Id")]
    public int SubtagId { get; set; }

    [ForeignKey("MoodboardId")]
    [InverseProperty("MoodboardSubTags")]
    public virtual Moodboard Moodboard { get; set; }

    [ForeignKey("SubtagId")]
    [InverseProperty("MoodboardSubTags")]
    public virtual SubTag Subtag { get; set; }
}