// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Viber.Models;

[Table("PrimaryTag")]
public partial class PrimaryTag
{
    [Key]
    [Column("PrimaryTag_Id")]
    public int PrimaryTagId { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string Name { get; set; }

    [InverseProperty("PrimaryTag")]
    public virtual ICollection<Moodboard> Moodboards { get; set; } = new List<Moodboard>();

    [InverseProperty("PrimaryTag")]
    public virtual ICollection<SubTag> SubTags { get; set; } = new List<SubTag>();
}