// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Viber.Models;

[Table("SubTag")]
public partial class SubTag
{
    [Key]
    [Column("SubTag_Id")]
    public int SubTagId { get; set; }

    [Required]
    [StringLength(20)]
    [Unicode(false)]
    public string Name { get; set; }

    [Column("PrimaryTag_Id")]
    public int PrimaryTagId { get; set; }

    [InverseProperty("Subtag")]
    public virtual ICollection<MoodboardSubTag> MoodboardSubTags { get; set; } = new List<MoodboardSubTag>();

    [ForeignKey("PrimaryTagId")]
    [InverseProperty("SubTags")]
    public virtual PrimaryTag PrimaryTag { get; set; }
}